test installing jq

diff --git a/JenkinsfileDeploy b/JenkinsfileDeploy
--- a/JenkinsfileDeploy
+++ b/JenkinsfileDeploy
@@ -30,11 +30,18 @@ node('docker') {
             Version Label: $userInput.versionLabel
         """
     }
-
-    stage('Setup') {
-        sh 'apk add jq'
+    
+    stage('Install jq (if necessary)') {
+        sh '''
+            if ! command -v jq &> /dev/null; then
+                echo "jq not found, installing..."
+                sudo apt-get update && sudo apt-get install -y jq
+            else
+                echo "jq is already installed."
+            fi
+        '''
     }
-
+    
     stage('Compute voucherHubStartBlock') {
         if (!userInput.voucherHubStartBlock) {
             // Compute the start block by fetching it from the Bellecour fork URL
